import { StyleSheet } from "react-native";

export const cameraStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#000",
  },
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  camera: {
    flex: 1,
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 34,
    backgroundColor: "rgba(0, 0, 0, 0.45)",
  },
  controlsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sideControl: {
    width: 56,
    height: 56,
  },
  captureButton: {
    width: 86,
    height: 86,
    borderRadius: 43,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#F3E7EE",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
  },
  captureButtonInner: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: "#FFFFFF",
  },
  permissionContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    backgroundColor: "#000",
  },
  permissionTitle: {
    marginBottom: 10,
    fontSize: 22,
    fontWeight: "700",
    color: "#FFFFFF",
    textAlign: "center",
  },
  permissionText: {
    fontSize: 15,
    lineHeight: 22,
    color: "#CFCFCF",
    textAlign: "center",
    marginBottom: 20,
  },
  permissionPressable: {
    backgroundColor: "#2A2A2A",
    borderRadius: 10,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  permissionPressableText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  previewContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  previewImage: {
    flex: 1,
  },
  previewBottomBar: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 24,
    backgroundColor: "rgba(0, 0, 0, 0.92)",
  },
  previewActionButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#4A4A4A",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1A1A1A",
  },
  previewActionText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  previewPrimaryButton: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F3E7EE",
  },
  previewPrimaryText: {
    color: "#111111",
    fontSize: 15,
    fontWeight: "700",
  },
  uploadContainer: {
    padding: 16,
    gap: 16,
    backgroundColor: "#000",
  },
  uploadCentered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    backgroundColor: "#000",
  },
  uploadCard: {
    backgroundColor: "#111",
    borderRadius: 12,
    padding: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: "#2A2A2A",
  },
  uploadImage: {
    width: "100%",
    height: 250,
    borderRadius: 10,
    backgroundColor: "#1A1A1A",
  },
  uploadLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFFFFF",
    marginTop: 4,
  },
  uploadValue: {
    fontSize: 13,
    lineHeight: 18,
    color: "#C7C7C7",
  },
  uploadStatusText: {
    fontSize: 16,
    color: "#FFFFFF",
    textAlign: "center",
  },
  uploadErrorText: {
    fontSize: 16,
    color: "#FF6B6B",
    textAlign: "center",
  },
  uploadEmptyText: {
    fontSize: 16,
    color: "#C7C7C7",
    textAlign: "center",
    paddingVertical: 24,
  },
  uploadButtonWrapper: {
    marginTop: 8,
    borderRadius: 8,
    overflow: "hidden",
  },
});
