import { StyleSheet } from "react-native";

const shadow = {
  boxShadow: "0px 18px 30px rgba(24, 32, 25, 0.08)",
} as const;

export const homeStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F6F7F3" },
  page: { flex: 1, backgroundColor: "#F6F7F3" },
  scrollContent: { paddingHorizontal: 18, paddingVertical: 24 },
  shell: { width: "100%", maxWidth: 1180, alignSelf: "center", gap: 28 },
  blob: { position: "absolute", borderRadius: 999, opacity: 0.9 },
  blobLeft: {
    width: 260,
    height: 260,
    top: -60,
    left: -80,
    backgroundColor: "#EAF3E3",
  },
  blobRight: {
    width: 220,
    height: 220,
    top: 120,
    right: -70,
    backgroundColor: "#FFF3DD",
  },
  heroCard: {
    backgroundColor: "rgba(255,255,255,0.88)",
    borderWidth: 1,
    borderColor: "#DDE4D9",
    borderRadius: 32,
    padding: 22,
    gap: 18,
    alignItems: "center",
    ...shadow,
  },
  sectionCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#DDE4D9",
    borderRadius: 32,
    padding: 24,
    gap: 12,
    ...shadow,
  },
  heroTitle: {
    color: "#182019",
    fontSize: 36,
    lineHeight: 42,
    fontWeight: "800",
    letterSpacing: -1.2,
    textAlign: "center",
  },
  heroSubtitle: {
    color: "#5D6A60",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
  },
  heroTagline: {
    color: "#2F6A3E",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 1.2,
    textAlign: "center",
  },
  eyebrow: {
    color: "#2F6A3E",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  cardTitle: {
    color: "#182019",
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "800",
    letterSpacing: -0.8,
  },
  cardBody: { color: "#5D6A60", fontSize: 15, lineHeight: 23 },
  actionRow: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  ctaLink: {
    borderWidth: 1,
    borderColor: "#DDE4D9",
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 13,
    overflow: "hidden",
  },
  ctaLinkPrimary: {
    backgroundColor: "#2F6A3E",
    borderColor: "#2F6A3E",
  },
  ctaLinkSecondary: {
    alignSelf: "flex-start",
    borderColor: "#DDE4D9",
    backgroundColor: "#F6F7F3",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 13,
    overflow: "hidden",
  },
  ctaLinkText: { fontSize: 14, fontWeight: "700", color: "#182019" },
  ctaLinkTextPrimary: { fontSize: 14, fontWeight: "700", color: "#FFFFFF" },
  ctaLinkTextSecondary: { fontSize: 14, fontWeight: "700", color: "#2F6A3E" },
  produceGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  produceChip: {
    backgroundColor: "#EEF5EB",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  produceChipText: { color: "#2F6A3E", fontSize: 13, fontWeight: "600" },
});
