import { StyleSheet } from "react-native";

export const produceStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F4F5EF",
  },
  container: {
    flex: 1,
    backgroundColor: "#F4F5EF",
    padding: 18,
    paddingTop: 32,
  },
  scrollView: {
    flex: 1,
    backgroundColor: "#F4F5EF",
  },
  scrollContent: {
    padding: 18,
    paddingTop: 20,
    paddingBottom: 170,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#DFE4DB",
    borderRadius: 24,
    padding: 18,
    gap: 14,
    boxShadow: "0px 18px 40px rgba(26, 41, 30, 0.08)",
  },
  title: {
    color: "#182019",
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: -0.6,
    lineHeight: 30,
  },
  detail: {
    color: "#5D6A60",
    fontSize: 14,
    lineHeight: 21,
  },
  produceItem: {
    paddingVertical: 14,
  },
  produceName: {
    color: "#182019",
    fontSize: 16,
    fontWeight: "600",
  },
  metaBox: {
    padding: 14,
    borderWidth: 1,
    borderColor: "#D7E2D3",
    borderRadius: 18,
    gap: 6,
    backgroundColor: "#F7FBF5",
  },
  metaText: {
    color: "#445148",
    fontSize: 14,
  },
  linkButton: {
    backgroundColor: "#EEF5EB",
    borderRadius: 999,
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  linkText: {
    color: "#214C2D",
    fontSize: 13,
    fontWeight: "700",
  },
  nutritionTable: {
    borderWidth: 1,
    borderColor: "#D7E2D3",
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
  },
  tableTitle: {
    color: "#182019",
    fontSize: 17,
    fontWeight: "800",
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#D7E2D3",
    backgroundColor: "#F7FBF5",
  },
  nutritionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: "#EEF2EC",
  },
  nutritionLabel: {
    color: "#182019",
    flex: 1,
    fontSize: 14,
    paddingRight: 10,
  },
  nutritionValue: {
    color: "#182019",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "right",
  },
  errorText: {
    fontSize: 18,
    color: "#B42318",
  },
  listContent: {
    paddingBottom: 12,
  },
  cartSection: {
    gap: 12,
  },
  qtyRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  qtyButton: {
    alignItems: "center",
    backgroundColor: "#F7FBF5",
    borderColor: "#D7E2D3",
    borderRadius: 12,
    borderWidth: 1,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  qtyButtonText: {
    color: "#182019",
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 24,
  },
  qtyValue: {
    color: "#182019",
    fontSize: 16,
    fontWeight: "700",
    minWidth: 76,
    textAlign: "center",
  },
  addToCartButton: {
    alignItems: "center",
    backgroundColor: "#2F6A3E",
    borderRadius: 18,
    justifyContent: "center",
    minHeight: 52,
    paddingHorizontal: 12,
  },
  addToCartText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  stickyFooter: {
    backgroundColor: "#F4F5EF",
    borderTopColor: "#DFE4DB",
    borderTopWidth: 1,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 12,
  },
  stickyFooterCard: {
    backgroundColor: "#FFFFFF",
    borderColor: "#DFE4DB",
    borderRadius: 18,
    borderWidth: 1,
    padding: 12,
  },
});
